namespaces:
    ekyna_commerce:
        label: label
        trans_domain: EkynaCommerce
        prefix: /commerce

permissions:
    Ekyna\Bundle\CommerceBundle\Model\Permission::STAT_CHART:
        label: permission.stat_chart
        trans_domain: EkynaCommerce
