ekyna_commerce_api:
    resource: 'routing/api.yaml'
    prefix:   /api/commerce

# TODO split commerce / settings
ekyna_commerce_admin:
    resource: 'routing/admin.yaml'
    prefix:   '%ekyna_admin.routing_prefix%/commerce'

ekyna_commerce_front:
    resource: 'routing/front.yaml'

when@dev:
    ekyna_commerce_dev:
        resource: 'routing/dev.yaml'
        prefix: /dev
