ekyna_commerce_audience_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.audience.controller:homeAction" }
    methods: GET

ekyna_commerce_audience_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.audience.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_audience_admin_synchronize:
    path: /synchronize
    defaults: { _controller: "ekyna_commerce.audience.controller:synchronizeAction" }
    methods: [GET]

ekyna_commerce_audience_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.audience.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_audience_admin_show:
    path: /{audienceId}/show
    defaults: { _controller: "ekyna_commerce.audience.controller:showAction" }
    methods: [GET]
    requirements:
        audienceId: \d+

ekyna_commerce_audience_admin_edit:
    path: /{audienceId}/edit
    defaults: { _controller: "ekyna_commerce.audience.controller:editAction" }
    methods: [GET|POST]
    requirements:
        audienceId: \d+

ekyna_commerce_audience_admin_toggle:
    path: /{audienceId}/toggle/{field}
    defaults: { _controller: "ekyna_commerce.audience.controller:toggleAction", field: default }
    methods: [GET]
    requirements:
        audienceId: \d+
        field: \w+

ekyna_commerce_audience_admin_remove:
    path: /{audienceId}/remove
    defaults: { _controller: "ekyna_commerce.audience.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        audienceId: \d+
