ekyna_commerce_cart_item_admin_add:
    path: /add
    defaults: { _controller: "ekyna_commerce.cart_item.controller:addAction" }
    methods: [GET|POST]
    requirements:
        cartId: \d+

ekyna_commerce_cart_item_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.cart_item.controller:newAction" }
    methods: [GET|POST]
    requirements:
        cartId: \d+

ekyna_commerce_cart_item_admin_configure:
    path: /{cartItemId}/configure
    defaults: { _controller: "ekyna_commerce.cart_item.controller:configureAction" }
    methods: [GET|POST]
    requirements:
        cartId: \d+
        cartItemId: \d+

ekyna_commerce_cart_item_admin_edit:
    path: /{cartItemId}/edit
    defaults: { _controller: "ekyna_commerce.cart_item.controller:editAction" }
    methods: [GET|POST]
    requirements:
        cartId: \d+
        cartItemId: \d+

ekyna_commerce_cart_item_admin_move_up:
    path: /{cartItemId}/move-up
    defaults: { _controller: "ekyna_commerce.cart_item.controller:moveUpAction" }
    methods: [GET]
    requirements:
        cartId: \d+
        cartItemId: \d+

ekyna_commerce_cart_item_admin_move_down:
    path: /{cartItemId}/move-down
    defaults: { _controller: "ekyna_commerce.cart_item.controller:moveDownAction" }
    methods: [GET]
    requirements:
        cartId: \d+
        cartItemId: \d+

ekyna_commerce_cart_item_admin_remove:
    path: /{cartItemId}/remove
    defaults: { _controller: "ekyna_commerce.cart_item.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        cartId: \d+
        cartItemId: \d+

ekyna_commerce_cart_item_admin_adjustment:
    resource: cart_item_adjustment.yml
    prefix: /{cartItemId}/adjustments
