ekyna_commerce_cart_attachment_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.cart_attachment.controller:newAction" }
    methods: [GET|POST]
    requirements:
        cartId: \d+

ekyna_commerce_cart_attachment_admin_edit:
    path: /{cartAttachmentId}/edit
    defaults: { _controller: "ekyna_commerce.cart_attachment.controller:editAction" }
    methods: [GET|POST]
    requirements:
        cartId: \d+
        cartAttachmentId: \d+

ekyna_commerce_cart_attachment_admin_update:
    path: /{cartAttachmentId}/update
    defaults: { _controller: "ekyna_commerce.cart_attachment.controller:updateAction" }
    methods: [GET]
    requirements:
        cartId: \d+
        cartAttachmentId: \d+

ekyna_commerce_cart_attachment_admin_remove:
    path: /{cartAttachmentId}/remove
    defaults: { _controller: "ekyna_commerce.cart_attachment.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        cartId: \d+
        cartAttachmentId: \d+

ekyna_commerce_cart_attachment_admin_download:
    path: /{cartAttachmentId}/download
    defaults: { _controller: "ekyna_commerce.cart_attachment.controller:downloadAction" }
    methods: [GET]
    requirements:
        cartId: \d+
        cartAttachmentId: \d+

ekyna_commerce_cart_attachment_admin_archive:
    path: /{cartAttachmentId}/archive
    defaults: { _controller: "ekyna_commerce.cart_attachment.controller:archiveAction" }
    methods: [GET]
    requirements:
        cartId: \d+
        cartAttachmentId: \d+
