ekyna_commerce_cart_item_adjustment_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.cart_item_adjustment.controller:newAction" }
    methods: [GET|POST]
    requirements:
        cartId: \d+
        cartItemId: \d+

ekyna_commerce_cart_item_adjustment_admin_edit:
    path: /{cartItemAdjustmentId}/edit
    defaults: { _controller: "ekyna_commerce.cart_item_adjustment.controller:editAction" }
    methods: [GET|POST]
    requirements:
        cartId: \d+
        cartItemId: \d+
        cartItemAdjustmentId: \d+

ekyna_commerce_cart_item_adjustment_admin_remove:
    path: /{cartItemAdjustmentId}/remove
    defaults: { _controller: "ekyna_commerce.cart_item_adjustment.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        cartId: \d+
        cartItemId: \d+
        cartItemAdjustmentId: \d+
