ekyna_commerce_coupon_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.coupon.controller:homeAction" }
    methods: [GET]

ekyna_commerce_coupon_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.coupon.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_coupon_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.coupon.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_coupon_admin_show:
    path: /{couponId}/show
    defaults: { _controller: "ekyna_commerce.coupon.controller:showAction" }
    methods: [GET]
    requirements:
        couponId: \d+

ekyna_commerce_coupon_admin_edit:
    path: /{couponId}/edit
    defaults: { _controller: "ekyna_commerce.coupon.controller:editAction" }
    methods: [GET|POST]
    requirements:
        couponId: \d+

ekyna_commerce_coupon_admin_remove:
    path: /{couponId}/remove
    defaults: { _controller: "ekyna_commerce.coupon.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        couponId: \d+
