ekyna_commerce_customer_contact_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.customer_contact.controller:newAction" }
    methods: [GET|POST]
    requirements:
        customerId: \d+

ekyna_commerce_customer_contact_admin_edit:
    path: /{customerContactId}/edit
    defaults: { _controller: "ekyna_commerce.customer_contact.controller:editAction" }
    methods: [GET|POST]
    requirements:
        customerId: \d+
        customerContactId: \d+

ekyna_commerce_customer_contact_admin_remove:
    path: /{customerContactId}/remove
    defaults: { _controller: "ekyna_commerce.customer_contact.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        customerId: \d+
        customerContactId: \d+
