ekyna_commerce_export_admin_accounting:
    path: /accounting
    methods: [POST]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:accounting }

ekyna_commerce_export_admin_due_invoices:
    path: /due-invoices
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:dueInvoices }

ekyna_commerce_export_admin_fall_invoices:
    path: /fall-invoices
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:fallInvoices }

ekyna_commerce_export_admin_remaining_orders:
    path: /remaining-orders
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:remainingOrders }

ekyna_commerce_export_admin_due_orders:
    path: /due-orders
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:dueOrders }

ekyna_commerce_export_admin_all_due_orders:
    path: /all-due-orders
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:allDueOrders }

ekyna_commerce_export_admin_regular_due_orders:
    path: /regular-due-orders
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:regularDueOrders }

ekyna_commerce_export_admin_outstanding_expired_due_orders:
    path: /outstanding-expired-due-orders
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:outstandingExpiredDueOrders }

ekyna_commerce_export_admin_outstanding_fall_due_orders:
    path: /outstanding-fall-due-orders
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:outstandingFallDueOrders }

ekyna_commerce_export_admin_outstanding_pending_due_orders:
    path: /outstanding-pending-due-orders
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:outstandingPendingDueOrders }

ekyna_commerce_export_admin_suppliers_expired_due_orders:
    path: /suppliers-expired-due-orders
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:suppliersExpiredDueOrders }

ekyna_commerce_export_admin_suppliers_fall_due_orders:
    path: /suppliers-fall-due-orders
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:suppliersFallDueOrders }

ekyna_commerce_export_admin_forwarders_expired_due_orders:
    path: /forwarders-expired-due-orders
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:forwardersExpiredDueOrders }

ekyna_commerce_export_admin_forwarders_fall_due_orders:
    path: /forwarders-fall-due-orders
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:forwardersFallDueOrders }

ekyna_commerce_export_admin_regions_orders_stats:
    path: /regions-orders-stats
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:regionsOrdersStats }

ekyna_commerce_export_admin_regions_invoices_stats:
    path: /regions-invoices-stats
    methods: [GET]
    defaults: { _controller: EkynaCommerceBundle:Admin\Export:regionsInvoicesStats }
