ekyna_commerce_admin_map:
    path: ""
    controller: Ekyna\Bundle\CommerceBundle\Controller\Admin\MapController::index
    methods: [GET]

ekyna_commerce_admin_map_data:
    path: /data
    controller: Ekyna\Bundle\CommerceBundle\Controller\Admin\MapController::data
    methods: [GET]
    options:
        expose: true
        i18n: false

ekyna_commerce_admin_map_info:
    path: /info
    controller: Ekyna\Bundle\CommerceBundle\Controller\Admin\MapController::info
    methods: [GET]
    options:
        expose: true
        i18n: false
