ekyna_commerce_order_shipment_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.order_shipment.controller:newAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+

ekyna_commerce_order_shipment_admin_gateway_form:
    path: /gateway-form/{shipmentMethodId}
    defaults: { _controller: "ekyna_commerce.order_shipment.controller:gatewayFormAction" }
    methods: [GET]
    requirements:
        orderId: \d+
        shipmentMethodId: \d+
    options:
        expose: true

ekyna_commerce_order_shipment_admin_edit:
    path: /{orderShipmentId}/edit
    defaults: { _controller: "ekyna_commerce.order_shipment.controller:editAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        orderShipmentId: \d+

ekyna_commerce_order_shipment_admin_ship:
    path: /{orderShipmentId}/ship
    defaults: { _controller: "ekyna_commerce.order_shipment.controller:shipAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        orderShipmentId: \d+

ekyna_commerce_order_shipment_admin_cancel:
    path: /{orderShipmentId}/cancel
    defaults: { _controller: "ekyna_commerce.order_shipment.controller:cancelAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        orderShipmentId: \d+

ekyna_commerce_order_shipment_admin_complete:
    path: /{orderShipmentId}/complete
    defaults: { _controller: "ekyna_commerce.order_shipment.controller:completeAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        orderShipmentId: \d+

ekyna_commerce_order_shipment_admin_print_label:
    path: /{orderShipmentId}/print-label
    defaults: { _controller: "ekyna_commerce.order_shipment.controller:printLabelAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        orderShipmentId: \d+

ekyna_commerce_order_shipment_admin_remove:
    path: /{orderShipmentId}/remove
    defaults: { _controller: "ekyna_commerce.order_shipment.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        orderShipmentId: \d+

ekyna_commerce_order_shipment_admin_render:
    path: /{orderShipmentId}/render/{type}.{_format}
    defaults:
        _controller: "ekyna_commerce.order_shipment.controller:renderAction"
        _format: pdf
    methods: [GET]
    requirements:
        orderId: \d+
        orderShipmentId: \d+
        type: shipment_form|shipment_bill
        _format: html|pdf|jpg

ekyna_commerce_order_shipment_admin_summary:
    path: /{orderShipmentId}/summary
    defaults: { _controller: "ekyna_commerce.order_shipment.controller:summaryAction" }
    methods: [GET]
    requirements:
        orderId: \d+
        orderShipmentId: \d+
    options:
        expose: true
