ekyna_commerce_order_invoice_admin_new:
    path: /new/{type}
    defaults: { _controller: "ekyna_commerce.order_invoice.controller:newAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        type: "[a-z]+"

ekyna_commerce_order_invoice_admin_edit:
    path: /{orderInvoiceId}/edit
    defaults: { _controller: "ekyna_commerce.order_invoice.controller:editAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        orderInvoiceId: \d+

ekyna_commerce_order_invoice_admin_remove:
    path: /{orderInvoiceId}/remove
    defaults: { _controller: "ekyna_commerce.order_invoice.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        orderInvoiceId: \d+

ekyna_commerce_order_invoice_admin_recalculate:
    path: /{orderInvoiceId}/recalculate
    defaults:
        _controller: "ekyna_commerce.order_invoice.controller:recalculateAction"
    methods: [GET]
    requirements:
        orderId: \d+
        orderInvoiceId: \d+

ekyna_commerce_order_invoice_admin_unlink:
    path: /{orderInvoiceId}/unlink
    defaults:
        _controller: "ekyna_commerce.order_invoice.controller:unlinkAction"
    methods: [GET]
    requirements:
        orderId: \d+
        orderInvoiceId: \d+

ekyna_commerce_order_invoice_admin_render:
    path: /{orderInvoiceId}/render.{_format}
    defaults:
        _controller: "ekyna_commerce.order_invoice.controller:renderAction"
        _format: pdf
    methods: [GET]
    requirements:
        orderId: \d+
        orderInvoiceId: \d+
        _format: html|pdf|jpg
