ekyna_commerce_quote_attachment_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.quote_attachment.controller:newAction" }
    methods: [GET|POST]
    requirements:
        quoteId: \d+

ekyna_commerce_quote_attachment_admin_edit:
    path: /{quoteAttachmentId}/edit
    defaults: { _controller: "ekyna_commerce.quote_attachment.controller:editAction" }
    methods: [GET|POST]
    requirements:
        quoteId: \d+
        quoteAttachmentId: \d+

ekyna_commerce_quote_attachment_admin_remove:
    path: /{quoteAttachmentId}/remove
    defaults: { _controller: "ekyna_commerce.quote_attachment.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        quoteId: \d+
        quoteAttachmentId: \d+

ekyna_commerce_quote_attachment_admin_download:
    path: /{quoteAttachmentId}/download
    defaults: { _controller: "ekyna_commerce.quote_attachment.controller:downloadAction" }
    methods: [GET]
    requirements:
        quoteId: \d+
        quoteAttachmentId: \d+

ekyna_commerce_quote_attachment_admin_archive:
    path: /{quoteAttachmentId}/archive
    defaults: { _controller: "ekyna_commerce.quote_attachment.controller:archiveAction" }
    methods: [GET]
    requirements:
        quoteId: \d+
        quoteAttachmentId: \d+
