ekyna_commerce_shipment_rule_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.shipment_rule.controller:homeAction" }
    methods: [GET]

ekyna_commerce_shipment_rule_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.shipment_rule.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_shipment_rule_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.shipment_rule.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_shipment_rule_admin_show:
    path: /{shipmentRuleId}/show
    defaults: { _controller: "ekyna_commerce.shipment_rule.controller:showAction" }
    methods: [GET]
    requirements:
        shipmentRuleId: \d+

ekyna_commerce_shipment_rule_admin_edit:
    path: /{shipmentRuleId}/edit
    defaults: { _controller: "ekyna_commerce.shipment_rule.controller:editAction" }
    methods: [GET|POST]
    requirements:
        shipmentRuleId: \d+

ekyna_commerce_shipment_rule_admin_remove:
    path: /{shipmentRuleId}/remove
    defaults: { _controller: "ekyna_commerce.shipment_rule.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        shipmentRuleId: \d+
