shipment_gateway_admin_list_relay_points:
    path: /{gateway}/list-relay-points
    defaults:
        _controller: EkynaCommerceBundle:Admin/ShipmentGateway:listRelayPoints
    requirements:
        gateway: "[a-zA-Z0-9-_]+"

shipment_gateway_admin_get_relay_point:
    path: /{gateway}/get-relay-point
    defaults:
        _controller: EkynaCommerceBundle:Admin/ShipmentGateway:getRelayPoint
    requirements:
        gateway: "[a-zA-Z0-9-_]+"