ekyna_commerce_shipment_platform_admin_export:
    path: /{platform}/export
    defaults:
        _controller: EkynaCommerceBundle:Admin/ShipmentPlatform:export
    requirements:
        platform: "[a-zA-Z0-9-_]+"

ekyna_commerce_shipment_platform_admin_import:
    path: /{platform}/import
    defaults:
        _controller: EkynaCommerceBundle:Admin/ShipmentPlatform:import
    requirements:
        platform: "[a-zA-Z0-9-_]+"
