ekyna_commerce_shipment_method_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.shipment_method.controller:homeAction" }
    methods: [GET]

ekyna_commerce_shipment_method_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.shipment_method.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_shipment_method_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.shipment_method.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_shipment_method_admin_show:
    path: /{shipmentMethodId}/show
    defaults: { _controller: "ekyna_commerce.shipment_method.controller:showAction" }
    methods: [GET]
    requirements:
        shipmentMethodId: \d+

ekyna_commerce_shipment_method_admin_edit:
    path: /{shipmentMethodId}/edit
    defaults: { _controller: "ekyna_commerce.shipment_method.controller:editAction" }
    methods: [GET|POST]
    requirements:
        shipmentMethodId: \d+

#ekyna_commerce_shipment_method_admin_tinymce:
#    path: /{shipmentMethodId}/tinymce/{_locale}/{field}
#    controller: "ekyna_commerce.shipment_method.controller:tinymceAction"
#    methods: [GET]
#    requirements:
#        shipmentMethodId: \d+
#        field: "[a-zA-Z0-9]+"
#    defaults:
#        _locale: "%locale%"
#        field: description

ekyna_commerce_shipment_method_admin_move_up:
    path: /{shipmentMethodId}/moveup
    defaults: { _controller: "ekyna_commerce.shipment_method.controller:moveUpAction" }
    methods: [GET]
    requirements:
        shipmentMethodId: \d+

ekyna_commerce_shipment_method_admin_move_down:
    path: /{shipmentMethodId}/movedown
    defaults: { _controller: "ekyna_commerce.shipment_method.controller:moveDownAction" }
    methods: [GET]
    requirements:
        shipmentMethodId: \d+

ekyna_commerce_shipment_method_admin_toggle:
    path: /{shipmentMethodId}/toggle/{field}
    defaults: { _controller: "ekyna_commerce.shipment_method.controller:toggleAction", field: enabled }
    methods: [GET]
    requirements:
        shipmentMethodId: \d+
        field: \w+

ekyna_commerce_shipment_method_admin_remove:
    path: /{shipmentMethodId}/remove
    defaults: { _controller: "ekyna_commerce.shipment_method.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        shipmentMethodId: \d+
