ekyna_commerce_supplier_template_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.supplier_template.controller:homeAction" }
    methods: [GET]

ekyna_commerce_supplier_template_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.supplier_template.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_supplier_template_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.supplier_template.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_supplier_template_admin_show:
    path: /{supplierTemplateId}/show
    defaults: { _controller: "ekyna_commerce.supplier_template.controller:showAction" }
    methods: [GET]
    requirements:
        supplierTemplateId: \d+

ekyna_commerce_supplier_template_admin_edit:
    path: /{supplierTemplateId}/edit
    defaults: { _controller: "ekyna_commerce.supplier_template.controller:editAction" }
    methods: [GET|POST]
    requirements:
        supplierTemplateId: \d+

ekyna_commerce_supplier_template_admin_remove:
    path: /{supplierTemplateId}/remove
    defaults: { _controller: "ekyna_commerce.supplier_template.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        supplierTemplateId: \d+
