ekyna_commerce_supplier_order_attachment_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.supplier_order_attachment.controller:newAction" }
    methods: [GET|POST]
    requirements:
        supplierOrderId: \d+

ekyna_commerce_supplier_order_attachment_admin_edit:
    path: /{supplierOrderAttachmentId}/edit
    defaults: { _controller: "ekyna_commerce.supplier_order_attachment.controller:editAction" }
    methods: [GET|POST]
    requirements:
        supplierOrderId: \d+
        supplierOrderAttachmentId: \d+

ekyna_commerce_supplier_order_attachment_admin_remove:
    path: /{supplierOrderAttachmentId}/remove
    defaults: { _controller: "ekyna_commerce.supplier_order_attachment.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        supplierOrderId: \d+
        supplierOrderAttachmentId: \d+

ekyna_commerce_supplier_order_attachment_admin_download:
    path: /{supplierOrderAttachmentId}/download
    defaults: { _controller: "ekyna_commerce.supplier_order_attachment.controller:downloadAction" }
    methods: [GET]
    requirements:
        supplierOrderId: \d+
        supplierOrderAttachmentId: \d+
