ekyna_commerce_supplier_carrier_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.supplier_carrier.controller:homeAction" }
    methods: [GET]

ekyna_commerce_supplier_carrier_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.supplier_carrier.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_supplier_carrier_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.supplier_carrier.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_supplier_carrier_admin_show:
    path: /{supplierCarrierId}/show
    defaults: { _controller: "ekyna_commerce.supplier_carrier.controller:showAction" }
    methods: [GET]
    requirements:
        supplierCarrierId: \d+

ekyna_commerce_supplier_carrier_admin_edit:
    path: /{supplierCarrierId}/edit
    defaults: { _controller: "ekyna_commerce.supplier_carrier.controller:editAction" }
    methods: [GET|POST]
    requirements:
        supplierCarrierId: \d+

ekyna_commerce_supplier_carrier_admin_remove:
    path: /{supplierCarrierId}/remove
    defaults: { _controller: "ekyna_commerce.supplier_carrier.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        supplierCarrierId: \d+
