ekyna_commerce_ticket_attachment_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.ticket_attachment.controller:newAction" }
    methods: [GET|POST]
    requirements:
        ticketId: \d+
        ticketMessageId: \d+
    options: { expose: true }

ekyna_commerce_ticket_attachment_admin_edit:
    path: /{ticketAttachmentId}/edit
    defaults: { _controller: "ekyna_commerce.ticket_attachment.controller:editAction" }
    methods: [GET|POST]
    requirements:
        ticketId: \d+
        ticketMessageId: \d+
        ticketAttachmentId: \d+
    options: { expose: true }

ekyna_commerce_ticket_attachment_admin_remove:
    path: /{ticketAttachmentId}/remove
    defaults: { _controller: "ekyna_commerce.ticket_attachment.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        ticketId: \d+
        ticketMessageId: \d+
        ticketAttachmentId: \d+
    options: { expose: true }
