ekyna_commerce_warehouse_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.warehouse.controller:homeAction" }
    methods: [GET]

ekyna_commerce_warehouse_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.warehouse.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_warehouse_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.warehouse.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_warehouse_admin_show:
    path: /{warehouseId}/show
    defaults: { _controller: "ekyna_commerce.warehouse.controller:showAction" }
    methods: [GET]
    requirements:
        warehouseId: \d+

ekyna_commerce_warehouse_admin_edit:
    path: /{warehouseId}/edit
    defaults: { _controller: "ekyna_commerce.warehouse.controller:editAction" }
    methods: [GET|POST]
    requirements:
        warehouseId: \d+

ekyna_commerce_warehouse_admin_remove:
    path: /{warehouseId}/remove
    defaults: { _controller: "ekyna_commerce.warehouse.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        warehouseId: \d+
