resources:
    ekyna_commerce:
        bill_of_materials:
            driver: doctrine/orm
            entity:
                interface: Ekyna\Component\Commerce\Manufacture\Model\BillOfMaterialsInterface
                class: Ekyna\Component\Commerce\Manufacture\Entity\BillOfMaterials
            repository:
                interface: Ekyna\Component\Commerce\Manufacture\Repository\BillOfMaterialsRepositoryInterface
                class: Ekyna\Component\Commerce\Bridge\Doctrine\ORM\Repository\BillOfMaterialsRepository
            normalizer: Ekyna\Component\Commerce\Bridge\Symfony\Serializer\Normalizer\BOMNormalizer
            form: Ekyna\Bundle\CommerceBundle\Form\Type\Manufacture\BillOfMaterialsType
            table: Ekyna\Bundle\CommerceBundle\Table\Type\BillOfMaterialsType
            trans_domain: EkynaCommerce
            actions:
                admin_crud:
                    form: '@EkynaCommerce/Admin/BillOfMaterials/_form.html.twig'
                    read: '@EkynaCommerce/Admin/BillOfMaterials/read.html.twig'
                    summary: '@EkynaCommerce/Admin/BillOfMaterials/summary.html.twig'
                    duplicate: true
                Ekyna\Bundle\CommerceBundle\Action\Admin\BillOfMaterials\ValidateAction: ~
                Ekyna\Bundle\CommerceBundle\Action\Admin\BillOfMaterials\ArchiveAction: ~
                Ekyna\Bundle\CommerceBundle\Action\Admin\BillOfMaterials\DuplicateAction: ~
                Ekyna\Bundle\CommerceBundle\Action\Admin\BillOfMaterials\CreatePOAction: ~

        bom_component:
            driver: doctrine/orm
            entity:
                interface: Ekyna\Component\Commerce\Manufacture\Model\BOMComponentInterface
                class: Ekyna\Component\Commerce\Manufacture\Entity\BOMComponent
            form: Ekyna\Bundle\CommerceBundle\Form\Type\Manufacture\BOMComponentType
            trans_domain: EkynaCommerce
            parent: ekyna_commerce.bill_of_materials

        production_order:
            driver: doctrine/orm
            entity:
                interface: Ekyna\Component\Commerce\Manufacture\Model\ProductionOrderInterface
                class: Ekyna\Component\Commerce\Manufacture\Entity\ProductionOrder
            repository:
                interface: Ekyna\Component\Commerce\Manufacture\Repository\ProductionOrderRepositoryInterface
                class: Ekyna\Component\Commerce\Bridge\Doctrine\ORM\Repository\ProductionOrderRepository
            normalizer: Ekyna\Component\Commerce\Bridge\Symfony\Serializer\Normalizer\ProductionOrderNormalizer
            form: Ekyna\Bundle\CommerceBundle\Form\Type\Manufacture\ProductionOrderType
            table: Ekyna\Bundle\CommerceBundle\Table\Type\ProductionOrderType
            trans_domain: EkynaCommerce
            actions:
                admin_crud:
                    form: '@EkynaCommerce/Admin/ProductionOrder/_form.html.twig'
                    create: false
                    list: '@EkynaCommerce/Admin/ProductionOrder/list.html.twig'
                    read:
                        template: '@EkynaCommerce/Admin/ProductionOrder/read.html.twig'
                        expose: true
                    update: '@EkynaCommerce/Admin/ProductionOrder/update.html.twig'
                    delete: '@EkynaCommerce/Admin/ProductionOrder/delete.html.twig'
                    summary: '@EkynaCommerce/Admin/ProductionOrder/summary.html.twig'
                Ekyna\Bundle\CommerceBundle\Action\Admin\ProductionOrder\CancelAction: ~
                Ekyna\Bundle\CommerceBundle\Action\Admin\ProductionOrder\CreateAction: ~
                Ekyna\Bundle\CommerceBundle\Action\Admin\ProductionOrder\GanttAction: ~
                Ekyna\Bundle\CommerceBundle\Action\Admin\ProductionOrder\PrioritizeAction: ~
                Ekyna\Bundle\CommerceBundle\Action\Admin\ProductionOrder\ScheduleAction: ~
                Ekyna\Bundle\CommerceBundle\Action\Admin\ProductionOrder\UpgradeAction: ~

        production_item:
            driver: doctrine/orm
            entity:
                interface: Ekyna\Component\Commerce\Manufacture\Model\ProductionItemInterface
                class: Ekyna\Component\Commerce\Manufacture\Entity\ProductionItem
            normalizer: Ekyna\Component\Commerce\Bridge\Symfony\Serializer\Normalizer\ProductionItemNormalizer
            trans_domain: EkynaCommerce
            parent: ekyna_commerce.production_order

        production_item_assignment:
            driver: doctrine/orm
            entity:
                class: Ekyna\Component\Commerce\Manufacture\Entity\ProductionItemAssignment
            parent: ekyna_commerce.production_item
            trans_prefix: assignment
            trans_domain: EkynaCommerce

        production:
            driver: doctrine/orm
            entity:
                interface: Ekyna\Component\Commerce\Manufacture\Model\ProductionInterface
                class: Ekyna\Component\Commerce\Manufacture\Entity\Production
            repository:
                interface: Ekyna\Component\Commerce\Manufacture\Repository\ProductionRepositoryInterface
                class: Ekyna\Component\Commerce\Bridge\Doctrine\ORM\Repository\ProductionRepository
            form: Ekyna\Bundle\CommerceBundle\Form\Type\Manufacture\ProductionType
            trans_domain: EkynaCommerce
            parent: ekyna_commerce.production_order
            actions:
                admin_crud:
                    form: '@EkynaCommerce/Admin/Production/_form.html.twig'
                    read: false
                    list: false
