fos_elastica:
    indexes:
        acme_product_product:
            types:
                doc:
                    serializer:
                        groups: [Search]
                    properties:
                        id: { type: integer }
                        text: { type: text }
                    dynamic_templates:
                        default:
                            match_mapping_type: string
                            mapping: {type: text}
                    persistence:
                        driver: orm
                        model: Acme\Product\Entity\Product
                        provider:
                            batch_size: 25
                        listener: ~
                        finder: ~
                        repository: Acme\ProductBundle\Service\Search\ProductRepository
