ekyna_commerce_api_shipment_gateway_list_relay_points:
    path: /{gateway}/list-relay-points
    methods: [GET]
    defaults:
        _controller: "ekyna_commerce.controller.api.shipment_gateway:listRelayPointsAction"
    requirements:
        gateway: "[a-zA-Z0-9-_]+"
    options:
        expose: true

ekyna_commerce_api_shipment_gateway_get_relay_point:
    path: /{gateway}/get-relay-point
    methods: [GET]
    defaults:
        _controller: "ekyna_commerce.controller.api.shipment_gateway:getRelayPointAction"
    requirements:
        gateway: "[a-zA-Z0-9-_]+"
    options:
        expose: true

