<?php

namespace Ekyna\Bundle\CommerceBundle\Show\Type;

use Ekyna\Bundle\AdminBundle\Show\Exception\InvalidArgumentException;
use Ekyna\Bundle\AdminBundle\Show\Type\AbstractType;
use Ekyna\Bundle\AdminBundle\Show\View;
use libphonenumber\PhoneNumber;

/**
 * Class PhoneType
 * @package Ekyna\Bundle\CommerceBundle\Show\Type
 * @author  Etienne Dauvergne <contact@ekyna.com>
 */
class PhoneType extends AbstractType
{
    /**
     * @inheritDoc
     */
    public function build(View $view, $value, array $options = [])
    {
        if ($value && !$value instanceof PhoneNumber) {
            throw new InvalidArgumentException("Expected instance of " . PhoneNumber::class);
        }

        parent::build($view, $value, $options); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getWidgetPrefix()
    {
        return 'commerce_phone';
    }
}
