ekyna_commerce_country_admin:
    resource: "admin/country.yml"
    prefix:   /countries

ekyna_commerce_currency_admin:
    resource: "admin/currency.yml"
    prefix:   /currencies

ekyna_commerce_customer_admin:
    resource: "admin/customer.yml"
    prefix:   /customers

ekyna_commerce_customer_group_admin:
    resource: "admin/customer_group.yml"
    prefix:   /customer-groups

ekyna_commerce_order_admin:
    resource: "admin/order.yml"
    prefix:   /orders

ekyna_commerce_payment_method_admin:
    resource: "admin/payment_method.yml"
    prefix:   /payment-methods

ekyna_commerce_payment_term_admin:
    resource: "admin/payment_term.yml"
    prefix:   /payment-terms

ekyna_commerce_quote_admin:
    resource: "admin/quote.yml"
    prefix:   /quotes

ekyna_commerce_shipment_method_admin:
    resource: "admin/shipment_method.yml"
    prefix:   /shipment-methods

ekyna_commerce_shipment_zone_admin:
    resource: "admin/shipment_zone.yml"
    prefix:   /shipment-zones

ekyna_commerce_supplier_admin:
    resource: "admin/supplier.yml"
    prefix:   /suppliers

ekyna_commerce_supplier_order_admin:
    resource: "admin/supplier_order.yml"
    prefix:   /supplier-orders

ekyna_commerce_tax_admin:
    resource: "admin/tax.yml"
    prefix:   /taxes

ekyna_commerce_tax_group_admin:
    resource: "admin/tax_group.yml"
    prefix:   /tax-groups

ekyna_commerce_tax_rule_admin:
    resource: "admin/tax_rule.yml"
    prefix:   /tax-rules

ekyna_commerce_admin_order_list_payment:
    path: /order-payments
    defaults: { _controller: EkynaCommerceBundle:Admin/OrderList:payment }
    methods: [GET]

ekyna_commerce_admin_order_list_shipment:
    path: /order-shipments
    defaults: { _controller: EkynaCommerceBundle:Admin/OrderList:shipment }
    methods: [GET]

ekyna_commerce_admin_order_list_shipment_platform_action:
    path: /order-shipments/platform/{name}/{action}
    defaults: { _controller: EkynaCommerceBundle:Admin/OrderList:platformAction }
    methods: [GET|POST]

ekyna_commerce_admin_order_list_invoice:
    path: /order-invoices
    defaults: { _controller: EkynaCommerceBundle:Admin/OrderList:invoice }
    methods: [GET]
