ekyna_commerce_api_customer:
    resource: "api/customer.yml"
    prefix: /customer

ekyna_commerce_api_pricing:
    resource: "api/pricing.yml"
    prefix: /pricing

ekyna_commerce_api_shippment_gateway:
    resource: "api/shipment_gateway.yml"
    prefix: /shipment-gateway
