ekyna_commerce_payment:
    resource: "front/payment.yml"
    prefix:   /payment

ekyna_commerce_cart:
    resource: "front/cart.yml"
    prefix:   /cart

ekyna_commerce_cart_checkout:
    resource: "front/cart-checkout.yml"
    prefix:   /my-cart

ekyna_commerce_account:
    resource: "front/account.yml"
    prefix:   /my-account
