ekyna_commerce_account_registration:
    resource: "account/registration.yml"
    prefix:   /registration

ekyna_commerce_account_information:
    resource: "account/information.yml"
    prefix:   /information

ekyna_commerce_account_balance:
    resource: "account/balance.yml"
    prefix:   /situation

ekyna_commerce_account_address:
    resource: "account/address.yml"
    prefix:   /addresses

ekyna_commerce_account_quote:
    resource: "account/quote.yml"
    prefix:   /quotes

ekyna_commerce_account_order:
    resource: "account/order.yml"
    prefix:   /orders

ekyna_commerce_account_invoice:
    resource: "account/invoice.yml"
    prefix:   /invoices

ekyna_commerce_account_payment_status:
    path: /payment/status
    defaults: { _controller: "ekyna_commerce.controller.account.payment:statusAction" }
    methods: [GET]

ekyna_commerce_account_loader:
    resource: .
    type: commerce_account
