ekyna_commerce_cart_checkout_index:
    path: ""
    controller: "ekyna_commerce.controller.cart_checkout:indexAction"
    methods: [GET, POST]
    options:
        _cms:
            name: Mon panier
            menus: [footer]
            locked: true
            advanced: false
            position: 50

ekyna_commerce_cart_checkout_quote:
    path: /transform-to-quote
    controller: "ekyna_commerce.controller.cart_checkout:quoteAction"
    methods: [GET, POST]
    options:
        _cms:
            name: Transformer en devis
            parent: ekyna_commerce_cart_checkout_index
            locked: true
            advanced: false
            seo:
                index: false
                follow: false

ekyna_commerce_cart_checkout_shipment:
    path: /shipment
    controller: "ekyna_commerce.controller.cart_checkout:shipmentAction"
    methods: [GET, POST]
    options:
        _cms:
            name: Livraison
            parent: ekyna_commerce_cart_checkout_index
            locked: true
            advanced: false
            seo:
                index: false
                follow: false

ekyna_commerce_cart_checkout_payment:
    path: /payment
    controller: "ekyna_commerce.controller.cart_checkout:paymentAction"
    methods: [GET, POST]
    options:
        _cms:
            name: Paiement
            parent: ekyna_commerce_cart_checkout_index
            locked: true
            advanced: false
            seo:
                index: false
                follow: false

ekyna_commerce_cart_checkout_unlock:
    path: /unlock
    controller: "ekyna_commerce.controller.cart_checkout:unlockAction"
    methods: [GET]

ekyna_commerce_cart_checkout_status:
    path: /status
    controller: "ekyna_commerce.controller.cart_checkout:statusAction"
    methods: [GET]

ekyna_commerce_cart_checkout_confirmation:
    path: /confirmation/{orderKey}
    controller: "ekyna_commerce.controller.cart_checkout:confirmationAction"
    methods: [GET]
    requirements:
        orderKey: "[a-zA-Z0-9]+"
    options:
        _cms:
            name: Confirmation
            parent: ekyna_commerce_cart_checkout_index
            locked: true
            advanced: false
            seo:
                index: false
                follow: false
