ekyna_commerce_cart_checkout_index:
    path: ""
    controller: Ekyna\Bundle\CommerceBundle\Controller\Cart\CheckoutController::index
    methods: [GET, POST]
    options:
        _cms:
            name: Mon panier
            menus: [footer]
            locked: true
            advanced: false
            position: 50

ekyna_commerce_cart_checkout_quote:
    path: /transform-to-quote
    controller: Ekyna\Bundle\CommerceBundle\Controller\Cart\CheckoutController::quote
    methods: [GET, POST]
    options:
        _cms:
            name: Transformer en devis
            parent: ekyna_commerce_cart_checkout_index
            locked: true
            advanced: false
            seo:
                index: false
                follow: false

ekyna_commerce_cart_checkout_shipment:
    path: /shipment
    controller: Ekyna\Bundle\CommerceBundle\Controller\Cart\CheckoutController::shipment
    methods: [GET, POST]
    options:
        _cms:
            name: Livraison
            parent: ekyna_commerce_cart_checkout_index
            locked: true
            advanced: false
            seo:
                index: false
                follow: false

ekyna_commerce_cart_checkout_payment:
    path: /payment
    controller: Ekyna\Bundle\CommerceBundle\Controller\Cart\CheckoutController::payment
    methods: [GET, POST]
    options:
        _cms:
            name: Paiement
            parent: ekyna_commerce_cart_checkout_index
            locked: true
            advanced: false
            seo:
                index: false
                follow: false

ekyna_commerce_cart_checkout_unlock:
    path: /unlock
    controller: Ekyna\Bundle\CommerceBundle\Controller\Cart\CheckoutController::unlock
    methods: [GET]

ekyna_commerce_cart_checkout_status:
    path: /status
    controller: Ekyna\Bundle\CommerceBundle\Controller\Cart\CheckoutController::status
    methods: [GET]

ekyna_commerce_cart_checkout_confirmation:
    path: /confirmation/{orderKey}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Cart\CheckoutController::confirmation
    methods: [GET]
    requirements:
        orderKey: "[a-zA-Z0-9]+"
    options:
        _cms:
            name: Confirmation
            parent: ekyna_commerce_cart_checkout_index
            locked: true
            advanced: false
            seo:
                index: false
                follow: false
