ekyna_commerce_newsletter_subscription:
    path: /subscription
    controller: Ekyna\Bundle\CommerceBundle\Controller\Front\NewsletterController::subscription
    methods: [GET, POST]
    options:
        _cms:
            name: Inscription à notre newsletter
            menus: [footer]
            locked: true
            advanced: true
            position: 90

ekyna_commerce_newsletter_subscribed:
    path: /subscribed
    controller: Ekyna\Bundle\CommerceBundle\Controller\Front\NewsletterController::subscribed
    methods: [GET]
    options:
        _cms:
            name: Confirmation d'inscription à la newsletter
            locked: true
            advanced: true
            position: 91
