ekyna_commerce_payment_capture:
    path: /capture/{payum_token}
    controller: Payum\Bundle\PayumBundle\Controller\CaptureController::doAction
    options: { i18n: false }

ekyna_commerce_payment_authorize:
    path: /authorize/{payum_token}
    controller: Payum\Bundle\PayumBundle\Controller\AuthorizeController::doAction
    options: { i18n: false }

ekyna_commerce_payment_payout:
    path: /payout/{payum_token}
    controller: Payum\Bundle\PayumBundle\Controller\PayoutController::doAction
    options: { i18n: false }

ekyna_commerce_payment_cancel:
    path: /cancel/{payum_token}
    controller: Payum\Bundle\PayumBundle\Controller\CancelController::doAction
    options: { i18n: false }

ekyna_commerce_payment_refund:
    path: /refund/{payum_token}
    controller: Payum\Bundle\PayumBundle\Controller\RefundController::doAction
    options: { i18n: false }

ekyna_commerce_payment_sync:
    path: /sync/{payum_token}
    controller: Payum\Bundle\PayumBundle\Controller\SyncController::doAction
    options: { i18n: false }

ekyna_commerce_payment_notify:
    path: /notify/{payum_token}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Payment\NotifyController::notify
    options: { i18n: false }

ekyna_commerce_payment_accept:
    path: /accept/{payum_token}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Payment\AcceptController::accept
    options: { i18n: false }

ekyna_commerce_payment_hang:
    path: /hang/{payum_token}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Payment\HangController::hang
    options: { i18n: false }

ekyna_commerce_payment_reject:
    path: /reject/{payum_token}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Payment\RejectController::reject
    options: { i18n: false }
