ekyna_commerce_subject_add_to_cart:
    path: /add-to-cart/{provider}/{identifier}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Subject\SubjectController:addToCart
    methods: GET|POST
    options: { i18n: false }
