ekyna_commerce_widget_customer_widget:
    path: /customer/widget
    defaults:
        _controller: "ekyna_commerce.controller.widget:customerWidgetAction"
    methods: [GET]
    options:
        expose: true

ekyna_commerce_widget_customer_dropdown:
    path: /customer/dropdown
    defaults:
        _controller: "ekyna_commerce.controller.widget:customerDropdownAction"
    methods: [GET]
    options:
        expose: true
        
ekyna_commerce_widget_cart_widget:
    path: /cart/widget
    defaults:
        _controller: "ekyna_commerce.controller.widget:cartWidgetAction"
    methods: [GET]
    options:
        expose: true

ekyna_commerce_widget_cart_dropdown:
    path: /cart/dropdown
    defaults:
        _controller: "ekyna_commerce.controller.widget:cartDropdownAction"
    methods: [GET]
    options:
        expose: true