ekyna_commerce_widget_customer_widget:
    path: /customer/widget
    controller: Ekyna\Bundle\CommerceBundle\Controller\WidgetController::customerWidget
    methods: GET
    options: { i18n: false }

ekyna_commerce_widget_customer_dropdown:
    path: /customer/dropdown
    controller: Ekyna\Bundle\CommerceBundle\Controller\WidgetController::customerDropdown
    methods: GET
    options: { i18n: false }
        
ekyna_commerce_widget_cart_widget:
    path: /cart/widget
    controller: Ekyna\Bundle\CommerceBundle\Controller\WidgetController::cartWidget
    methods: GET
    options: { i18n: false }

ekyna_commerce_widget_cart_dropdown:
    path: /cart/dropdown
    controller: Ekyna\Bundle\CommerceBundle\Controller\WidgetController::cartDropdown
    methods: GET
    options: { i18n: false }

ekyna_commerce_widget_context_widget:
    path: /context/widget
    controller: Ekyna\Bundle\CommerceBundle\Controller\WidgetController::contextWidget
    methods: GET
    options: { i18n: false }

ekyna_commerce_widget_context_dropdown:
    path: /context/dropdown
    controller: Ekyna\Bundle\CommerceBundle\Controller\WidgetController::contextDropdown
    methods: GET
    options: { i18n: false }

ekyna_commerce_widget_context_change:
    path: /context/change
    controller: Ekyna\Bundle\CommerceBundle\Controller\WidgetController::contextChange
    methods: POST
    options: { i18n: false }

ekyna_commerce_widget_currency_change:
    path: /currency/change
    controller: Ekyna\Bundle\CommerceBundle\Controller\WidgetController::currencyChange
    methods: POST
    options: { i18n: false }
