ekyna_commerce_account_address_index:
    path: ""
    defaults:
        _controller: EkynaCommerceBundle:Account/Address:index
    methods: [GET]
    options:
        _cms:
            name: Mes adresses
            parent: ekyna_user_account_index
            position: 60
            locked: true
            advanced: false
            seo:
                follow: false
                index: false

ekyna_commerce_account_address_add:
    path: /add
    defaults:
        _controller: EkynaCommerceBundle:Account/Address:add
    methods: [GET|POST]

ekyna_commerce_account_address_edit:
    path: /{addressId}/edit
    defaults:
        _controller: EkynaCommerceBundle:Account/Address:edit
    methods: [GET|POST]
    requirements:
        addressId: \d+

ekyna_commerce_account_address_remove:
    path: /{addressId}/remove
    defaults:
        _controller: EkynaCommerceBundle:Account/Address:remove
    methods: [GET|POST]
    requirements:
        addressId: \d+

ekyna_commerce_account_address_default_invoice:
    path: /{addressId}/default-invoice
    defaults:
        _controller: EkynaCommerceBundle:Account/Address:invoiceDefault
    methods: [GET]
    requirements:
        addressId: \d+

ekyna_commerce_account_address_default_delivery:
    path: /{addressId}/default-delivery
    defaults:
        _controller: EkynaCommerceBundle:Account/Address:deliveryDefault
    methods: [GET]
    requirements:
        addressId: \d+
