ekyna_commerce_account_balance_index:
    path: ""
    defaults:
        _controller: EkynaCommerceBundle:Account/Balance:index
    methods: [GET, POST]
    options:
        _cms:
            name: Situation de mon compte
            parent: ekyna_user_account_index
            position: 15
            locked: true
            advanced: false
            seo:
                follow: false
                index: false
