ekyna_commerce_account_loyalty_index:
    path: ''
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\LoyaltyController::index
    methods: [GET]
    options:
        ekyna_i18n: ~
        _cms:
            name: Points de fidélité
            parent: ekyna_user_account_index
            position: 10
            locked: true
            advanced: false
            seo:
                follow: false
                index: false
