ekyna_commerce_account_newsletter_index:
    path: ""
    defaults:
        _controller: EkynaCommerceBundle:Account/Newsletter:index
    methods: [GET]
    options:
        _cms:
            name: Newsletter
            parent: ekyna_user_account_index
            position: 10
            locked: true
            advanced: false
            seo:
                follow: false
                index: false
