ekyna_commerce_account_order_index:
    path: ''
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\Order\IndexController
    methods: [GET]
    options:
        ekyna_i18n: ~
        _cms:
            name: Mes commandes
            parent: ekyna_user_account_index
            position: 30
            locked: true
            advanced: false
            seo:
                follow: false
                index: false

ekyna_commerce_account_order_read:
    path: /{number}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\Order\ReadController
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: GET
    options:
        ekyna_i18n: ~

ekyna_commerce_account_order_export:
    path:
        en: /{number}/export.{_format}
        fr: /{number}/exporter.{_format}
        es: /{number}/exportar.{_format}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\Order\ExportController
    requirements:
        number: "[a-zA-Z0-9]+"
        _format: "csv|xls"
    methods: GET
    options:
        ekyna_i18n: ~

ekyna_commerce_account_order_payment:
    resource: order/payment.yaml
    prefix:
        en: /{number}/payments
        fr: /{number}/paiments
        es: /{number}/pagos

ekyna_commerce_account_order_shipment_download:
    path:
        en: /{number}/shipments/{id}/download.{_format}
        fr: /{number}/expeditions/{id}/telecharger.{_format}
        es: /{number}/envios/{id}/descargar.{_format}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\Order\Shipment\DownloadController
    defaults:
        _format: pdf
    requirements:
        number: "[a-zA-Z0-9]+"
        id: \d+
        _format: pdf|html|jpg
    methods: [GET]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_order_invoice_download:
    path:
        en: /{number}/invoices/{id}/download.{_format}
        fr: /{number}/factures/{id}/telecharger.{_format}
        es: /{number}/facturas/{id}/descargar.{_format}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\Order\Invoice\DownloadController
    defaults:
        _format: pdf
    requirements:
        number: "[a-zA-Z0-9]+"
        id: \d+
        _format: pdf|html|jpg
    methods: [GET]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_order_attachment:
    resource: order/attachment.yaml
    prefix:
        en: /{number}/documents
        fr: /{number}/documents
        es: /{number}/documentos
