ekyna_commerce_account_order_index:
    path: ""
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:index
    methods: [GET]
    options:
        _cms:
            name: Mes commandes
            parent: ekyna_user_account_index
            position: 30
            locked: true
            advanced: false
            seo:
                follow: false
                index: false

ekyna_commerce_account_order_show:
    path: /{number}
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:show
    methods: [GET]

ekyna_commerce_account_order_payment:
    path: /{number}/payment
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:payment
    methods: [GET, POST]

ekyna_commerce_account_order_attachment_download:
    path: /{number}/documents/{id}
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:attachmentDownload
    methods: [GET]
