ekyna_commerce_account_order_index:
    path: ""
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:index
    methods: [GET]
    options:
        _cms:
            name: Mes commandes
            parent: ekyna_user_account_index
            position: 30
            locked: true
            advanced: false
            seo:
                follow: false
                index: false

ekyna_commerce_account_order_show:
    path: /{number}
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:show
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: GET
    options: {expose: true}

ekyna_commerce_account_order_export:
    path: /{number}/export.{_format}
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:export
    requirements:
        number: "[a-zA-Z0-9]+"
        _format: "csv|xls"
    methods: GET
    options: {i18n: false}

ekyna_commerce_account_order_payment_create:
    path: /{number}/payments/create
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:paymentCreate
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: [GET, POST]

ekyna_commerce_account_order_payment_cancel:
    path: /{number}/payments/{key}/cancel
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:paymentCancel
    requirements:
        number: "[a-zA-Z0-9]+"
        key: "[a-zA-Z0-9]+"
    methods: [GET, POST]

ekyna_commerce_account_order_shipment_download:
    path: /{number}/shipments/{id}/download.{_format}
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:shipmentDownload
        _format: pdf
    requirements:
        number: "[a-zA-Z0-9]+"
        id: \d+
        _format: pdf|html|jpg
    methods: [GET]

ekyna_commerce_account_order_invoice_download:
    path: /{number}/invoices/{id}/download.{_format}
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:invoiceDownload
        _format: pdf
    requirements:
        number: "[a-zA-Z0-9]+"
        id: \d+
        _format: pdf|html|jpg
    methods: [GET]

ekyna_commerce_account_order_attachment_create:
    path: /{number}/documents/create
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:attachmentCreate
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: [GET, POST]

ekyna_commerce_account_order_attachment_download:
    path: /{number}/documents/{id}/download
    defaults:
        _controller: EkynaCommerceBundle:Account/Order:attachmentDownload
    requirements:
        number: "[a-zA-Z0-9]+"
        id: \d+
    methods: [GET]
