ekyna_commerce_account_order_index:
    path: ''
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\OrderController::index
    methods: [GET]
    options:
        ekyna_i18n: ~
        _cms:
            name: Mes commandes
            parent: ekyna_user_account_index
            position: 30
            locked: true
            advanced: false
            seo:
                follow: false
                index: false

ekyna_commerce_account_order_read:
    path: /{number}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\OrderController::read
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: GET
    options:
        ekyna_i18n: ~

ekyna_commerce_account_order_export:
    path:
        en: /{number}/export.{_format}
        fr: /{number}/exporter.{_format}
        es: /{number}/exportar.{_format}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\OrderController::export
    requirements:
        number: "[a-zA-Z0-9]+"
        _format: "csv|xls"
    methods: GET
    options:
        ekyna_i18n: ~

ekyna_commerce_account_order_payment_create:
    path:
        en: /{number}/payments/create
        fr: /{number}/paiments/creer
        es: /{number}/pagos/crear
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\OrderController::paymentCreate
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: [GET, POST]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_order_payment_cancel:
    path:
        en: /{number}/payments/{key}/cancel
        fr: /{number}/paiments/{key}/annuler
        es: /{number}/pagos/{key}/cancelar
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\OrderController::paymentCancel
    requirements:
        number: "[a-zA-Z0-9]+"
        key: "[a-zA-Z0-9]+"
    methods: [GET, POST]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_order_shipment_download:
    path:
        en: /{number}/shipments/{id}/download.{_format}
        fr: /{number}/expeditions/{id}/telecharger.{_format}
        es: /{number}/envios/{id}/descargar.{_format}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\OrderController::shipmentDownload
    defaults:
        _format: pdf
    requirements:
        number: "[a-zA-Z0-9]+"
        id: \d+
        _format: pdf|html|jpg
    methods: [GET]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_order_invoice_download:
    path:
        en: /{number}/invoices/{id}/download.{_format}
        fr: /{number}/factures/{id}/telecharger.{_format}
        es: /{number}/facturas/{id}/descargar.{_format}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\OrderController::invoiceDownload
    defaults:
        _format: pdf
    requirements:
        number: "[a-zA-Z0-9]+"
        id: \d+
        _format: pdf|html|jpg
    methods: [GET]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_order_attachment_create:
    path:
        en: /{number}/documents/create
        fr: /{number}/documents/creer
        es: /{number}/documentos/crear
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\OrderController::attachmentCreate
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: [GET, POST]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_order_attachment_download:
    path:
        en: /{number}/documents/{id}/download
        fr: /{number}/documents/{id}/telecharger
        es: /{number}/documentos/{id}/descargar
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\OrderController::attachmentDownload
    requirements:
        number: "[a-zA-Z0-9]+"
        id: \d+
    methods: [GET]
    options:
        ekyna_i18n: ~
