ekyna_commerce_account_quote_index:
    path: ''
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\Quote\IndexController
    methods: [ GET ]
    options:
        ekyna_i18n: ~
        _cms:
            name: Mes devis
            parent: ekyna_user_account_index
            position: 20
            locked: true
            advanced: false
            seo:
                follow: false
                index: false

ekyna_commerce_account_quote_read:
    path: /{number}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\Quote\ReadController
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: [ GET ]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_export:
    path:
        en: /{number}/export.{_format}
        fr: /{number}/exporter.{_format}
        es: /{number}/exportar.{_format}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\Quote\ExportController
    requirements:
        number: "[a-zA-Z0-9]+"
        _format: "csv|xls"
    methods: [ GET ]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_refresh:
    path:
        en: /{number}/refresh
        fr: /{number}/recharger
        es: /{number}/actualizar
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\Quote\RefreshController
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: [ GET ]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_recalculate:
    path:
        en: /{number}/recalculate
        fr: /{number}/recalculer
        es: /{number}/recalcular
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\Quote\RecalculateController
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: [ GET, POST ]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_voucher:
    path:
        en: /{number}/voucher
        fr: /{number}/bon-d-achat
        es: /{number}/vale
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\Quote\VoucherController
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: [ GET, POST ]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_address:
    resource: quote/address.yaml
    prefix:
        en: /{number}
        fr: /{number}
        es: /{number}

ekyna_commerce_account_quote_attachment:
    resource: quote/attachment.yaml
    prefix:
        en: /{number}/documents
        fr: /{number}/documents
        es: /{number}/documentos

ekyna_commerce_account_quote_item:
    resource: quote/item.yaml
    prefix: /{number}/item
    requirements:
        number: "[a-zA-Z0-9]+"

ekyna_commerce_account_quote_payment:
    resource: quote/payment.yaml
    prefix:
        en: /{number}/payments
        fr: /{number}/paiments
        es: /{number}/pagos
