ekyna_commerce_account_quote_item_add:
    path: /add
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteItemController::add
    methods: GET|POST
    options: {expose: true}

ekyna_commerce_account_quote_item_configure:
    path: /{id}/configure
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteItemController::configure
    requirements:
        id: \d+
    methods: GET|POST
    options: {expose: true}

ekyna_commerce_account_quote_item_move_up:
    path: /{id}/move-up
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteItemController::moveUp
    requirements:
        id: \d+
    methods: GET
    options: {expose: true}

ekyna_commerce_account_quote_item_move_down:
    path: /{id}/move-down
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteItemController::moveDown
    requirements:
        id: \d+
    methods: GET|POST
    options: {expose: true}

ekyna_commerce_account_quote_item_remove:
    path: /{id}/remove
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteItemController::remove
    requirements:
        id: \d+
    methods: GET|POST
    options: {expose: true}
