ekyna_commerce_account_quote_index:
    path: ""
    defaults:
        _controller: EkynaCommerceBundle:Account/Quote:index
    methods: [GET]
    options:
        _cms:
            name: Mes devis
            parent: ekyna_user_account_index
            position: 40
            locked: true
            advanced: false
            seo:
                follow: false
                index: false

ekyna_commerce_account_quote_show:
    path: /{number}
    defaults:
        _controller: EkynaCommerceBundle:Account/Quote:show
    methods: [GET]

ekyna_commerce_account_quote_payment:
    path: /{number}/payment
    defaults:
        _controller: EkynaCommerceBundle:Account/Quote:payment
    methods: [GET, POST]

ekyna_commerce_account_quote_attachment_download:
    path: /{number}/documents/{id}
    defaults:
        _controller: EkynaCommerceBundle:Account/Quote:attachmentDownload
    methods: [GET]

