ekyna_commerce_account_quote_index:
    path: ""
    defaults:
        _controller: EkynaCommerceBundle:Account/Quote:index
    methods: [GET]
    options:
        _cms:
            name: Mes devis
            parent: ekyna_user_account_index
            position: 20
            locked: true
            advanced: false
            seo:
                follow: false
                index: false

ekyna_commerce_account_quote_show:
    path: /{number}
    defaults:
        _controller: EkynaCommerceBundle:Account/Quote:show
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: [GET]

ekyna_commerce_account_quote_voucher:
    path: /{number}/voucher
    defaults:
        _controller: EkynaCommerceBundle:Account/Quote:voucher
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: [GET, POST]

ekyna_commerce_account_quote_payment_create:
    path: /{number}/payments/create
    defaults:
        _controller: EkynaCommerceBundle:Account/Quote:paymentCreate
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: [GET, POST]

ekyna_commerce_account_quote_payment_cancel:
    path: /{number}/payments/{key}/cancel
    defaults:
        _controller: EkynaCommerceBundle:Account/Quote:paymentCancel
    requirements:
        number: "[a-zA-Z0-9]+"
        key: "[a-zA-Z0-9]+"
    methods: [GET, POST]

ekyna_commerce_account_quote_attachment_create:
    path: /{number}/documents/create
    defaults:
        _controller: EkynaCommerceBundle:Account/Quote:attachmentCreate
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: [GET, POST]

ekyna_commerce_account_quote_attachment_download:
    path: /{number}/documents/{id}/download
    defaults:
        _controller: EkynaCommerceBundle:Account/Quote:attachmentDownload
    requirements:
        number: "[a-zA-Z0-9]+"
        id: \d+
    methods: [GET]

