ekyna_commerce_account_quote_index:
    path: ''
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteController::index
    methods: [GET]
    options:
        ekyna_i18n: ~
        _cms:
            name: Mes devis
            parent: ekyna_user_account_index
            position: 20
            locked: true
            advanced: false
            seo:
                follow: false
                index: false

ekyna_commerce_account_quote_read:
    path: /{number}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteController::read
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: GET
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_export:
    path:
        en: /{number}/export.{_format}
        fr: /{number}/exporter.{_format}
        es: /{number}/exportar.{_format}
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteController::export
    requirements:
        number: "[a-zA-Z0-9]+"
        _format: "csv|xls"
    methods: GET
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_refresh:
    path:
        en: /{number}/refresh
        fr: /{number}/recharger
        es: /{number}/actualizar
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteController::refresh
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: GET
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_recalculate:
    path:
        en: /{number}/recalculate
        fr: /{number}/recalculer
        es: /{number}/recalcular
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteController::recalculate
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: GET|POST
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_voucher:
    path:
        en: /{number}/voucher
        fr: /{number}/bon-d-achat
        es: /{number}/vale
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteController::voucher
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: GET|POST
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_payment_create:
    path:
        en: /{number}/payments/create
        fr: /{number}/paiments/creer
        es: /{number}/pagos/crear
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteController::paymentCreate
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: GET|POST
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_payment_cancel:
    path:
        en: /{number}/payments/{key}/cancel
        fr: /{number}/paiments/{key}/annuler
        es: /{number}/pagos/{key}/cancelar
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteController::paymentCancel
    requirements:
        number: "[a-zA-Z0-9]+"
        key: "[a-zA-Z0-9]+"
    methods: GET|POST
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_attachment_create:
    path:
        en: /{number}/documents/create
        fr: /{number}/documents/creer
        es: /{number}/documentos/crear
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteController::attachmentCreate
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: GET|POST
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_attachment_download:
    path:
        en: /{number}/documents/{id}/download
        fr: /{number}/documents/{id}/telecharger
        es: /{number}/documentos/{id}/descargar
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteController::attachmentDownload
    requirements:
        number: "[a-zA-Z0-9]+"
        id: \d+
    methods: [GET]
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_invoice_address:
    path:
        en: /{number}/invoice-address
        fr: /{number}/adresse-de-facturation
        es: /{number}/direccion-de-facturacion
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteController::invoiceAddress
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: GET|POST
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_delivery_address:
    path:
        en: /{number}/delivery-address
        fr: /{number}/adresse-de-livraison
        es: /{number}/direccion-de-entrega
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\QuoteController::deliveryAddress
    requirements:
        number: "[a-zA-Z0-9]+"
    methods: GET|POST
    options:
        ekyna_i18n: ~

ekyna_commerce_account_quote_item:
    resource: quote_item.yaml
    prefix: /{number}/item
    requirements:
        number: "[a-zA-Z0-9]+"
