# Ticket
ekyna_commerce_account_ticket_index:
    path: ''
    methods: [GET]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketController::index
    options:
        ekyna_i18n: ~
        _cms:
            name: Mes tickets
            parent: ekyna_user_account_index
            position: 70
            locked: true
            advanced: false
            seo:
                follow: false
                index: false

ekyna_commerce_account_ticket_create:
    path: /create
    methods: [GET|POST]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketController::create
    options:
        expose: true

ekyna_commerce_account_ticket_update:
    path: /{ticketId}/update
    methods: [GET|POST]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketController::update
    requirements:
        ticketId: \d+
    options:
        expose: true

ekyna_commerce_account_ticket_delete:
    path: /{ticketId}/delete
    methods: [GET|POST]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketController::delete
    requirements:
        ticketId: \d+
    options:
        expose: true

ekyna_commerce_account_ticket_close:
    path: /{ticketId}/close
    methods: [GET|POST]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketController::close
    requirements:
        ticketId: \d+
    options:
        expose: true

ekyna_commerce_account_ticket_open:
    path: /{ticketId}/open
    methods: [GET|POST]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketController::open
    requirements:
        ticketId: \d+
    options:
        expose: true

# Message
ekyna_commerce_account_ticket_message_create:
    path: /{ticketId}/messages/create
    methods: [GET|POST]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketMessageController::create
    requirements:
        ticketId: \d+
    options:
        expose: true

ekyna_commerce_account_ticket_message_update:
    path: /{ticketId}/messages/{ticketMessageId}/update
    methods: [GET|POST]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketMessageController::update
    requirements:
        ticketId: \d+
        ticketMessageId: \d+
    options:
        expose: true

ekyna_commerce_account_ticket_message_delete:
    path: /{ticketId}/messages/{ticketMessageId}/delete
    methods: [GET|POST]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketMessageController::delete
    requirements:
        ticketId: \d+
        ticketMessageId: \d+
    options:
        expose: true

# Attachment
ekyna_commerce_account_ticket_attachment_create:
    path: /{ticketId}/messages/{ticketMessageId}/attachments/create
    methods: [GET|POST]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketAttachmentController::create
    requirements:
        ticketId: \d+
        ticketMessageId: \d+
    options:
        expose: true

ekyna_commerce_account_ticket_attachment_update:
    path: /{ticketId}/messages/{ticketMessageId}/attachments/{ticketAttachmentId}/update
    methods: [GET|POST]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketAttachmentController::update
    requirements:
        ticketId: \d+
        ticketMessageId: \d+
        ticketAttachmentId: \d+
    options:
        expose: true

ekyna_commerce_account_ticket_attachment_delete:
    path: /{ticketId}/messages/{ticketMessageId}/attachments/{ticketAttachmentId}/delete
    methods: [GET|POST]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketAttachmentController::delete
    requirements:
        ticketId: \d+
        ticketMessageId: \d+
        ticketAttachmentId: \d+
    options:
        expose: true

ekyna_commerce_account_ticket_attachment_download:
    path: /{ticketId}/messages/{ticketMessageId}/attachments/{ticketAttachmentId}/download
    methods: [GET]
    controller: Ekyna\Bundle\CommerceBundle\Controller\Account\TicketAttachmentController::download
    requirements:
        ticketId: \d+
        ticketMessageId: \d+
        ticketAttachmentId: \d+
    options:
        expose: true
